version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
  web:
    build:
      context: .
      dockerfile: tools/docker/Dockerfile
    image: 437884575683.dkr.ecr.us-west-2.amazonaws.com/pacifica-website-private:pacifica-web-0-1
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped
    expose:
      - 8000
  static:
    build:
      context: .
      dockerfile: tools/docker/staticDockerfile
    image: 437884575683.dkr.ecr.us-west-2.amazonaws.com/pacifica-website-private:pacifica-frontend-0-1
    ports:
      - "80:80"
    volumes:
      - ./prancerfrontend:/src
