# Generated by Django 3.2.6 on 2021-08-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='FIRST_NAME_MISSING', max_length=70)),
                ('last_name', models.CharField(default='LAST_NAME_MISSING', max_length=70)),
                ('abcs_id', models.CharField(default='', max_length=200)),
                ('am_notes_id', models.CharField(default='', max_length=200)),
                ('pm_notes_id', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=70)),
                ('name', models.CharField(default='', max_length=200)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
