# Generated by Django 3.2.6 on 2021-08-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=70)),
                ('name', models.CharField(default='', max_length=200)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
