# Generated by Django 3.2.7 on 2021-09-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacifica_visualizer', '0001_initial_squashed_0010_auto_20210904_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailynote',
            name='headers',
            field=models.CharField(default='HEADERS', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='dailynote',
            name='raw_data',
            field=models.CharField(default='RAW_DATA', max_length=5000, null=True),
        ),
    ]
