# Generated by Django 3.2.7 on 2021-09-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacifica_visualizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(default='TIMESTAMP', max_length=70)),
                ('message', models.CharField(default='TIMESTAMP', max_length=500)),
                ('username', models.CharField(default='TIMESTAMP', max_length=70)),
            ],
        ),
    ]
