# Generated by Django 3.2.7 on 2021-09-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacifica_visualizer', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.CharField(default='TIMESTAMP', max_length=70),
        ),
    ]
